version: '3'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      - app

  app:
    build:
      context: .
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: npm start
    expose:
      - 3333
    networks:
      - node-network
    tty: true
    depends_on:
      - db

  db:
    image: mariadb
    command: --init-file /data/application/init.sql
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
